CSRCS += \
	hif.c \
	hif_fifo.c \
	hif_dma.c \
	hif_uart.c \
	hif_hspi.c \
	lwip_ping.c \
	lwip_socket.c \
	atcmd_main.c \
	atcmd_core.c \
	atcmd_cli.c \
	atcmd_fota.c \
	atcmd_basic.c \
	atcmd_wifi.c \
	atcmd_socket.c \
	atcmd_test.c \
	atcmd_user.c
