CSRCS += \
	hif.c \
	hif_fifo.c \
	hif_uart.c \
	hif_hspi.c \
	atcmd_main.c \
	atcmd_core.c \
	atcmd_dump.c \
	atcmd_trace.c \
	atcmd_basic.c \
	atcmd_wifi.c \
	atcmd_socket.c \
	atcmd_perf.c \
	atcmd_test.c \
	lwip_ping.c \
	lwip_socket.c