#// --------------------------------------------------
#// FEATURE CONFIG
#// --------------------------------------------------
ifeq ($(CONFIG_S1G_HOOK), y)
DEFINE += -DINCLUDE_S1G_HOOK -DINCLUDE_S1G_CONFIG
endif # CONFIG_S1G_HOOK

ifeq ($(CONFIG_S1G_HOOK_BYPASS), y)
DEFINE += -DINCLUDE_S1G_HOOK_BYPASS
endif # CONFIG_S1G_HOOK_BYPASS

ifeq ($(CONFIG_UMAC_PRESP), y)
DEFINE += -DINCLUDE_UMAC_PRESP
endif # CONFIG_UMAC_PRESP

ifeq ($(CONFIG_MODEM_RECOVERY), y)
DEFINE += -DINCLUDE_MODEM_RECOVERY
#DEFINE += -DINCLUDE_OPTIMAL_CMD_SET
endif # CONFIG_MODEM_RECOVERY

ifeq ($(CONFIG_NEW_CHANNEL_CTX), y)
DEFINE += -DINCLUDE_NEW_CHANNEL_CTX
endif # CONFIG_NEW_CHANNEL_CTX

ifeq ($(CONFIG_APPLY_TX_GAIN_1_5_WITH_TXLO_TXIMG_CAL), y)
DEFINE	+= -DTX_GAIN_1_5_WITH_TXLO_TXIMG_CAL
endif # CONFIG_APPLY_TX_GAIN_1_5_WITH_TXLO_TXIMG_CAL

ifeq ($(CONFIG_USE_TEMP_SENSOR), y)
DEFINE	+= -DUSE_TEMP_SENSOR
endif # CONFIG_USE_TEMP_SENSOR

ifeq ($(CONFIG_USE_EEPROM), y)
DEFINE	+= -DUSE_EEPROM
DEFINE  += -DCAT24C64
endif # CONFIG_USE_EEPROM

ifeq ($(CONFIG_KR_MIC_SCAN), y)
DEFINE += -DINCLUDE_MIC_SCAN
DEFINE += -DINCLUDE_4M_OP_2M_TX
endif # CONFIG_MIC_SCAN

ifeq ($(CONFIG_DUTYCYCLE), y)
DEFINE += -DINCLUDE_DUTYCYCLE
DEFINE += -DINCLUDE_DUTY_CYCLE_CHECK
endif # CONFIG_DUTYCYCLE

ifeq ($(CONFIG_SILEX), y)
DEFINE += -DINCLUDE_SILEX
DEFINE += -DINCLUDE_GPIO_SILEX
endif # CONFIG_SILEX

ifeq ($(CONFIG_UCODE), y)
DEFINE += -DINCLUDE_UCODE
endif # CONFIG_UCODE

ifeq ($(CONFIG_TWT), y)
DEFINE += -DINCLUDE_TWT_SUPPORT

ifeq ($(CONFIG_MODEM_PS_HALT), y)
DEFINE += -DINCLUDE_MODEM_PS_HALT
endif # CONFIG_MODEM_PS_HALT

endif # CONFIG_TWT

ifeq ($(CONFIG_CONVERT_NON_QOSDATA), y)
DEFINE += -DINCLUDE_CONVERT_NON_QOSDATA
endif # CONFIG_CONVERT_NON_QOSDATA

ifeq ($(CONFIG_H2E), y)
DEFINE += -DINCLUDE_H2E_SUPPORT
endif # CONFIG_H2E

ifeq ($(CONFIG_WTS), y)
DEFINE += -DUMAC_CONFIG_WTS
endif # CONFIG_WTS
ifeq ($(CONFIG_BITMAP_ENCODING), y)
DEFINE += -DCONFIG_BITMAP_ENCODING
ifeq ($(CONFIG_REVERSE_SCRAMBLER), y)
DEFINE += -DCONFIG_REVERSE_SCRAMBLER
endif #CONFIG_REVERSE_SCRAMBLER
endif #CONFIG_BITMAP_ENCODING

ifeq ($(CONFIG_BG_SCAN), y)
DEFINE	+= -DCONFIG_BG_SCAN
endif # CONFIG_BG_SCAN

ifeq ($(CONFIG_PS_NONPOLL), y)
DEFINE += -DINCLUDE_PS_NONPOLL
endif # CONFIG_PS_NONPOLL

ifeq ($(CONFIG_BD), y)
DEFINE += -DINCLUDE_BD_SUPPORT
DEFINE += -DINCLUDE_BD_SUPPORT_TARGET_VERSION
endif # CONFIG_BD

ifeq ($(CONFIG_PMF_SWENC),y)
DEFINE += -DINCLUDE_PMF_SWENC
endif # CONFIG_PMF_SWENC

ifeq ($(CONFIG_RUNRAM),y)
DEFINE += -DINCLUDE_RUNRAM
endif # CONFIG_RUNRAM

ifeq ($(CONFIG_SET_WIM_BY_WQ),y)
DEFINE += -DINCLUDE_SET_WIM_BY_WQ
endif # CONFIG_SET_WIM_BY_WQ

ifeq ($(CONFIG_DL_TRANSMIT_BY_WQ),y)
DEFINE += -DINCLUDE_DL_TRANSMIT_BY_WQ
endif # CONFIG_DL_TRANSMIT_BY_WQ

ifeq ($(CONFIG_STA_SIG_INFO),y)
DEFINE += -DINCLUDE_STA_SIG_INFO
endif # CONFIG_STA_SIG_INFO

ifeq ($(CONFIG_WPS_PS_HOOK),y)
DEFINE += -DINCLUDE_WPS_PS_HOOK
endif # CONFIG_WPS_PS_HOOK

ifeq ($(CONFIG_1MBW_CENTER_LO),y)
#For 1M Bandwidth Center LO
DEFINE += -DBW1M_CENTER_LO_EU
DEFINE += -DBW1M_CENTER_LO_JP
DEFINE += -DBW1M_CENTER_LO_KR_USN1
endif # CONFIG_1MBW_CENTER_LO

ifeq ($(CONFIG_PRIMASK_INT_LOCK),y)
DEFINE += -DINCLUDE_PRIMASK_INT_LOCK
endif # CONFIG_PRIMASK_INT_LOCK

ifeq ($(CONFIG_NEW_TASK_ARCH),y)
DEFINE += -DINCLUDE_NEW_TASK_ARCH
DEFINE += -DINCLUDE_NO_USE_LMAC_SEM
ifeq ($(CONFIG_WDT),y)
DEFINE += -DINCLUDE_WDT
#DEFINE += -DINCLUDE_WDT_INT
endif # CONFIG_WDT
endif # CONFIG_NEW_TASK_ARCH

ifeq ($(CONFIG_AVOID_FRAG_ATTACK),y)
DEFINE += -DINCLUDE_AVOID_FRAG_ATTACK
#DEFINE += -DINCLUDE_AVOID_FRAG_ATTACK_TEST
endif # CONFIG_AVOID_FRAG_ATTACK

ifeq ($(CONFIG_STA_CSA_SUPPORT),y)
DEFINE += -DINCLUDE_STA_CSA_SUPPORT
endif # CONFIG_STA_CSA_SUPPORT

ifeq ($(CONFIG_WOWLAN_PATTERN),y)
DEFINE += -DINCLUDE_WOWLAN_PATTERN
endif # CONFIG_WOWLAN_PATTERN

ifeq ($(CONFIG_DYNAMIC_FRAG),y)
DEFINE += -DINCLUDE_DYNAMIC_FRAG
#Fragmented MPDU has no-linked buffer to save buffer
DEFINE += -DINCLUDE_DYNAMIC_FRAG_NO_LINKED
#Wait for buffer alloc with rety
#DEFINE += -DINCLUDE_DYNAMIC_FRAG_RETRY_ALLOC
endif # CONFIG_FRAGMENT_FRAME

ifeq ($(CONFIG_DEFRAG),y)
DEFINE += -DINCLUDE_DEFRAG
#DEFINE += -DINCLUDE_DEFRAG_CHECK_PN
endif # CONFIG_DEFRAG

ifeq ($(CONFIG_SUPPORT_IBSS),y)
DEFINE += -DINCLUDE_IBSS
endif # CONFIG_SUPPORT_IBSS

ifeq ($(CONFIG_CN_TEST_CH),y)
DEFINE += -DINCLUDE_CN_TEST_CH
endif # CONFIG_CN_TEST_CH

ifeq ($(CONFIG_RF_KILL),y)
DEFINE += -DINCLUDE_RF_KILL
DEFINE += -DINCLUDE_RF_KILL_IDLE
endif # CONFIG_RF_KILL

ifeq ($(CONFIG_BCAST_FOTA_AP),y)
DEFINE += -DINCLUDE_BCAST_FOTA_AP_SUPPORT
endif # CONFIG_BCAST_FOTA_AP

ifeq ($(CONFIG_BCAST_FOTA_STA),y)
DEFINE += -DINCLUDE_BCAST_FOTA_STA_SUPPORT
endif # CONFIG_BCAST_FOTA_STA

ifeq ($(CONFIG_MEASURE_AIRTIME),y)
DEFINE += -DINCLUDE_MEASURE_AIRTIME
endif # CONFIG_MEASURE_AIRTIME

ifeq ($(CONFIG_MEASURE_AIRTIME_NONESL),y)
DEFINE += -DINCLUDE_MEASURE_AIRTIME_NONESL
endif # CONFIG_MEASURE_AIRTIME_NONESL

ifeq ($(CONFIG_PS_DEBUG_ALWAYSONMEM),y)
DEFINE += -DINCLUDE_PS_DEBUG_ALWAYSONMEM
endif # CONFIG_PS_DEBUG_ALWAYSONMEM

ifeq ($(CONFIG_AUTH_CONTROL),y)
DEFINE += -DINCLUDE_AUTH_CONTROL
endif # CONFIG_AUTH_CONTROL

ifeq ($(CONFIG_SCAN_MODE),y)
DEFINE += -DINCLUDE_SCAN_MODE
#DEFINE += -DINCLUDE_SCAN_MODE_PHASE2
endif # CONFIG_SCAN_MODE

ifeq ($(CONFIG_DMA_COPY),y)
DEFINE += -DINCLUDE_GDMA_COPY
endif #CONFIG_DMA_COPY

ifeq ($(CONFIG_AMPDU_AUTO_TX),y)
#On SAM, automatically trigger to send ADDBA.
DEFINE += -DINCLUDE_AMPDU_AUTO_TX
endif #CONFIG_AMPDU_AUTO_TX

ifeq ($(CONFIG_AMPDU_REORDER),y)
#Copy frame located in system rx buffer to heap
#and free the system rx buffer early before data/mgmt_rx()
#This is to improve Rx Tput and AMPUDU Reordering
DEFINE += -DINCLUDE_EARLY_FREE_SYSRXBUF
DEFINE += -DINCLUDE_AMPDU_REORDER
DEFINE += -DINCLUDE_SIMPLE_REORDER_QUEUE
#DEFINE += -DINCLUDE_STATIC_REORDER_INFO
endif #CONFIG_AMPDU_REORDER

ifeq ($(CONFIG_CONVERT_BLOCK_ACK),y)
DEFINE += -DINCLUDE_CONVERT_BLOCK_ACK
endif #CONFIG_CONVERT_BLOCK_ACK

ifeq ($(CONFIG_NEW_V_SNPRINTF_SUPPORT),y)
DEFINE += -DNEW_V_SNPRINTF_SUPPORT
endif #CONFIG_NEW_V_SNPRINTF_SUPPORT

ifeq ($(CONFIG_REMOTECMD),y)
DEFINE += -DINCLUDE_VENDOR_REMOTECMD
endif # CONFIG_REMOTECMD

ifeq ($(CONFIG_SOFT_AP),y)
DEFINE += -DINCLUDE_SOFT_AP
DEFINE += -DSOFT_AP_BSS_MAX_IDLE
endif # CONFIG_SOFT_AP

ifeq ($(CONFIG_RTC_ALWAYS_ON),y)
DEFINE += -DINCLUDE_RTC_ALWAYS_ON
endif # CONFIG_RTC_ALWAYS_ON

ifeq ($(CONFIG_NRC7392_UCODE_TEST),y)
DEFINE += -DINCLUDE_NRC7392_UCODE_TEST
endif # CONFIG_NRC7392_UCODE_TEST

ifeq ($(CONFIG_MANUAL_AGG_NUM),y)
DEFINE += -DINCLUDE_MANUAL_AGG_NUM
endif # CONFIG_MANUAL_AGG_NUM

ifeq ($(CONFIG_SOFTAP_OWE),y)
DEFINE += -DINCLUDE_SOFTAP_OWE
endif

ifeq ($(CONFIG_PS_SCHEDULE),y)
DEFINE += -DINCLUDE_PS_SCHEDULE
endif # CONFIG_PS_SCHEDULE

ifeq ($(CONFIG_LEGACY_ACK),y)
DEFINE += -DINCLUDE_LEGACY_ACK
endif # CONFIG_LEGACY_ACK

ifeq ($(CONFIG_BEACON_BYPASS),y)
DEFINE += -DINCLUDE_BEACON_BYPASS
endif

ifeq ($(CONFIG_RF_BLOCKER),y)
DEFINE += -DINCLUDE_RF_BLOCKER
endif # CONFIG_RF_BLOCKER

ifeq ($(CONFIG_TSF_SYNC_VENDOR_IE),y)
DEFINE += -DINCLUDE_TSF_SYNC_VENDOR_IE
endif # CONFIG_TSF_SYNC_VENDOR_IE

ifeq ($(CONFIG_TSF_SYNC_PROBE_REQ),y)
DEFINE += -DINCLUDE_TSF_SYNC_PROBE_REQ
endif # CONFIG_TSF_SYNC_PROBE_REQ

ifeq ($(CONFIG_7393_7394_WORKAROUND),y)
DEFINE += -DINCLUDE_7393_7394_WORKAROUND
endif # CONFIG_7393_7394_WORKAROUND

ifeq ($(CONFIG_MODEM_SLEEP),y)
DEFINE += -DINCLUDE_MODEM_SLEEP
endif # CONIFG_MODEM_SLEEP

ifeq ($(CONFIG_SFLASH_DP),y)
DEFINE += -DINCLUDE_SFLASH_DP
endif # CONFIG_SFLASH_DP

ifeq ($(CONFIG_SFLASH_PAGE_PROG),y)
DEFINE += -DINCLUDE_SF_PAGE_PROG
endif # CONFIG_SFLASH_PAGE_PROG

ifeq ($(CONFIG_EXT_RAM),y)
DEFINE += -DINCLUDE_EXT_RAM
endif # CONFIG_EXT_RAM

ifeq ($(CONFIG_MATCH_OP_BW_PREQ_PRSP),y)
DEFINE += -DMATCH_OP_BW_PREQ_PRSP
endif # CONFIG_MATCH_OP_BW_PREQ_PRSP

ifeq ($(CONFIG_MANUAL_CONT_TX_SUPPORT),y)
DEFINE += -DINCLUDE_MANUAL_CONT_TX_SUPPORT
endif # CONFIG_MANUAL_CONT_TX_SUPPORT

ifeq ($(CONFIG_STA_SUPPORT_8M),y)
DEFINE += -DINCLUDE_STA_SUPPORT_8M
endif # CONFIG_STA_SUPPORT_8M

ifeq ($(CONFIG_RF_RECOVERY_BY_BCM),y)
DEFINE += -DINCLUDE_RF_RECOVERY_BY_BCM
endif # CONFIG_RF_RECOVERY_BY_BCM
